# -*- coding: utf-8 -*-
"""IDS 2.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K9roIdQETm46VugpZnSk2YC0yXgB0ND0
"""

def dls(node, goal, limit, path):
    if node == goal:
        return path

    if limit == 0:
        return None

    for child in graph[node]:
        if child not in path:
            result = dls(child, goal, limit - 1, path + [child])
            if result:
                return result

    return None


def ids(start, goal):
    depth = 0

    while True:
        print("Depth Limit:", depth)

        result = dls(start, goal, depth, [start])

        if result:
            return result

        depth += 1


# Graph
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F', 'G'],
    'D': [],
    'E': ['H'],
    'F': [],
    'G': [],
    'H': []
}

start = 'A'
goal = 'H'

path = ids(start, goal)

print("\nSolution Path:", " -> ".join(path))
print("Steps:", len(path) - 1)

