# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kp-6kehRbuJl3Es_1o3omMMkvgow9uLR
"""

def vacuum_cleaner(location, statusA, statusB):
    print(f"Initial State -> Location: {location}, A: {statusA}, B: {statusB}\n")

    while statusA == "DIRTY" or statusB == "DIRTY":

        if location == "A":
            if statusA == "DIRTY":
                print("Cleaning A...")
                statusA = "CLEAN"
            else:
                print("Moving Right (A → B)")
                location = "B"

        elif location == "B":
            if statusB == "DIRTY":
                print("Cleaning B...")
                statusB = "CLEAN"
            else:
                print("Moving Left (B → A)")
                location = "A"

        print(f"Current State -> Location: {location}, A: {statusA}, B: {statusB}\n")

    print("✅ All rooms are CLEAN!")


# ---- Example Run ----
vacuum_cleaner("A", "DIRTY", "DIRTY")

