# -*- coding: utf-8 -*-
"""WEEK 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CCkk-1BSFBqn64HT7hPOiq4ebqF3mf6y
"""

import heapq

goal = (1,2,3,4,5,6,7,8,0)

def misplaced(s):
    return sum(s[i] != goal[i] and s[i] != 0 for i in range(9))

def manhattan(s):
    return sum(abs(i//3-goal.index(x)//3) +
               abs(i%3-goal.index(x)%3)
               for i,x in enumerate(s) if x)

def astar(start, heuristic):
    pq = [(heuristic(start), 0, start, [])]
    visited = set()

    while pq:
        f, g, state, path = heapq.heappop(pq)

        if state in visited:
            continue
        visited.add(state)

        if state == goal:
            return path + [state]

        z = state.index(0)
        r, c = divmod(z, 3)

        for dr, dc in [(1,0),(-1,0),(0,1),(0,-1)]:
            nr, nc = r+dr, c+dc

            if 0 <= nr < 3 and 0 <= nc < 3:
                nz = nr*3 + nc
                new = list(state)
                new[z], new[nz] = new[nz], new[z]
                new = tuple(new)

                heapq.heappush(pq,
                    (g+1+heuristic(new), g+1, new, path+[state]))

start = tuple(map(int, input("Enter 9 values (0=blank): ").split()))

print("\n1. Misplaced Tiles")
print("2. Manhattan Distance")
choice = int(input("Choose: "))

h = misplaced if choice == 1 else manhattan
solution = astar(start, h)

for s in solution:
    print(s[:3])
    print(s[3:6])
    print(s[6:])
    print()

